// <auto-generated />
namespace Resume.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addsomeattributes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addsomeattributes));
        
        string IMigrationMetadata.Id
        {
            get { return "201612030121263_add some attributes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
